"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

DATA_FILES = ['View/Main.xib', 'View/Question.xib', 'View/Rule.xib', 'View/SimpleAnswer.xib', 'View/MCQAnswer.xib']
OPTIONS = {'argv_emulation': True, 'iconfile' : 'assets/exp.icns'}

setup(
	name="Experience Sampling",
	app=['Main.py'],
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
